### ISSUE TITLE
Try/catch block

### ISSUE THREAD

**Issue by IanaKhitsko** [ValeronMEN/CSharpRepos#10]
https://github.com/ValeronMEN/CSharpRepos/blob/1d0a987840ddd0ce926370765501a79f5a5fd08b/tpps_practice2/Program.cs#L29-L32

This external try/catch.. Is it applied to Convert.ToInt32 only? If so, maybe to wrap only this convertion?

**Comment by ValeronMEN** [comment]
Fixed in "try / catch; if / else fixed" update.

Close the issue, if you don't have any questions
