### ISSUE TITLE
Coin addition is not according to the requirements of the task

### ISSUE THREAD

**Issue by bbehrang** [ValeronMEN/CSharpRepos#3]
https://github.com/ValeronMEN/CSharpRepos/blob/master/tpps_practice2/City.cs#L74

according to the task, every day a representative portion of coins, based on the city’s beginning day balance, is transported to each neighbor of the city. A representative portion is defined as one coin for every full 1000 coins of a motif. Random variable should be removed and the representative portion should be used in its place.

**Comment by ValeronMEN** [comment]
I don't agree with this task requirements interpretation. Let Hitzko judge

**Comment by ValeronMEN** [comment]
Done
