### ISSUE TITLE
Unnecessary operations according to the task.

### ISSUE THREAD

**Issue by bbehrang** [ValeronMEN/CSharpRepos#4]
https://github.com/ValeronMEN/CSharpRepos/blob/master/tpps_practice2/City.cs#L26
https://github.com/ValeronMEN/CSharpRepos/blob/master/tpps_practice2/City.cs#L81
https://github.com/ValeronMEN/CSharpRepos/blob/master/tpps_practice2/City.cs#L86

According to the task once a motif reaches 1000 it can be transferred to another city, therefore this variable and the prevention seem unnecessary.

**Comment by ValeronMEN** [comment]
It's part of another issue:
https://github.com/ValeronMEN/CSharpRepos/issues/3
