### ISSUE TITLE
Performance issue in the coin addition loop

### ISSUE THREAD

**Issue by bbehrang** [ValeronMEN/CSharpRepos#5]
https://github.com/ValeronMEN/CSharpRepos/blob/master/tpps_practice2/City.cs#L50

going through a loop of 1,000,000 cycles to add items to a list drastically affects the performance. Consider creating either a class which holds the number of coin and its motif instead of adding coins one by one.

**Comment by ValeronMEN** [comment]
Yes, it affects the perfomance, but there's no specific requirement in the task conditions

Close the issue, if you don't have any questions

**Comment by ValeronMEN** [comment]
In the last version there's no perfomance issue
