### ISSUE TITLE
Coin distribution issue

### ISSUE THREAD

**Issue by bbehrang** [ValeronMEN/CSharpRepos#6]
https://github.com/ValeronMEN/CSharpRepos/blob/master/tpps_practice2/Eurozone.cs#L78
 coin distribution is done according to the order and not the representative portion of motifs

**Comment by ValeronMEN** [comment]
I didn't understand the question. Explain it in another way

**Comment by bbehrang** [comment]
what will happen in a case in which you transfer 999 coins of a motif 'A', 1 coin of motif 'B', and 1001 of motif 'A'? as I understood you will make 2 transfers, first transfer will be 999 of 'A' and 1 of 'B', second will be 1000 of 'A'. so you transfer motif 'B' without letting it reach the required (1000) amount

**Comment by ValeronMEN** [comment]
Got it. I've fixed it
