### ISSUE TITLE
Ambiguous logic

### ISSUE THREAD

**Issue by bbehrang** [ValeronMEN/CSharpRepos#8]
https://github.com/ValeronMEN/CSharpRepos/blob/master/tpps_practice2/Eurozone.cs#L55

Since countries are connected using cities, the need of going through another loop to check if countries are neighbors seems redundant. Please provide an explanation of the logic behind this function.

**Comment by ValeronMEN** [comment]
It provides avoiding an error when countries have a gap between each other, like this: Ukraine 1 1 2 2 and Iran 4 1 5 2. In this example the countries don't have neighbours, so there will be a permanent loop without checking connection

Close the issue, if you don't have any questions

**Comment by bbehrang** [comment]
Please label the question as "extra help required"
