### ISSUE TITLE
Revert condition

### ISSUE THREAD

**Issue by IanaKhitsko** [ValeronMEN/CSharpRepos#9]
https://github.com/ValeronMEN/CSharpRepos/blob/1d0a987840ddd0ce926370765501a79f5a5fd08b/tpps_practice2/Program.cs#L36

Consider making less indents for functional code. As an option (I dont insist), here you can just write 

if (countryCount < 0 || countryCount > 20)
{
  // some error
  return false;
}

//Code for correct scenario

**Comment by ValeronMEN** [comment]
Fixed in "try / catch; if / else fixed" update.

Close the issue, if you don't have any questions
